version: "3.8"

services:
  shard-worker:
    build: .
    ports:
      - "${WORKER_PORT}:${WORKER_PORT}"
    environment:
      - WORKER_PORT=${WORKER_PORT}
      - WORKER_TOKEN=${WORKER_TOKEN}
      - FLOAT_USER=${FLOAT_USER}
      - FLOAT_PASS=${FLOAT_PASS}
      - FLOAT_AWS_SG=${FLOAT_AWS_SG}
      - FLOAT_CORES=${FLOAT_CORES}
      - FLOAT_MEMORY=${FLOAT_MEMORY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
