name: Build & Test

on:
  pull_request:

env:
  TERM: xterm
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.24.5"

      - name: Build & Test
        run: make
